### PR TITLE
Added largeClass.md and a link to README.md

### PR DESCRIPTION
**Pull request by Niyy**

### CODE REVIEW

**Comment by Niyy** [comment]
This is the best merge ever since it adds large class examples.

**Comment by Niyy** [comment]
Add it now Buffardi!

**Comment by kbuffardi** [comment]
Please use hyphenated file names

**Comment by Niyy** [comment]
https://media.giphy.com/media/3o84sw9CmwYpAnRRni/giphy.gif

**Comment by kbuffardi** [comment]
Close... but "example of" is inconsistent with the formatting of the rest of the list

**Pull request merged**
