### PR TITLE
Dead Code

### PR DESCRIPTION
**Pull request by JennGriff**
Adding bullet : Dead Code to Read.md with a link to example

### CODE REVIEW

**Comment by kbuffardi** [comment]
Make sure not only to resolve the conflict, but also merge your work into `dead-code.md`

**Comment by kbuffardi** [comment]
`dead_code.md` should be `dead-code.md`

**Comment by JennGriff** [comment]
changed dead_code.md to dead-code.md

**Comment by kbuffardi** [comment]
Make sure to resolve the current conflicts

**Pull request closed without merging**
